dbt_project:
  target: LOCAL
  outputs:
    LOCAL: 
      type: duckdb
      path: ../example.duckdb
      schema: vehicles
    GCP:
      dataset: "{{ env_var('GCP_BQ_DATASET') }}"
      project: "{{ env_var('GCP_BQ_PROJECT') }}"
      method: service-account
      threads: 1
      type: bigquery
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"