version: 2

sources:
  - name: "vehicles"
    schema: |
      {%- if  target.name == "GCP" -%} {{ env_var('GCP_BQ_DATASET') }}
      {%- else -%} vehicles
      {%- endif -%}
    tables:
    - name: "plant_data"