name: Serverless Prod Deployment
on:
  schedule:
    - cron: '0 8 * * thu'
  push:
    branches:
      - "main"
      - "master"
concurrency:
  # Cancel in-progress deploys to main branch
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: "http://hooli-demo.canary.dagster.cloud"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  

jobs:
  parse_workspace:
    name: Parse Workspace
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}

    steps:
      - name: Parse cloud workspace
        id: parse-workspace
        uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
        with:
          dagster_cloud_file: dagster_cloud.yaml
  
  dagster_cloud_docker_deploy:
    name: Dagster Serverless Docker Deploy
    runs-on: ubuntu-latest
    needs: parse_workspace
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_workspace.outputs.build_info) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout dagster master
        uses: actions/checkout@v3
        with:
          repository: dagster-io/dagster
          path: ./dagster

      - name: Checkout dagster-cloud master from internal
        shell: bash
        env:
          PAT: ${{ secrets.DAGSTER_INTERNAL_CLONE_PAT }}
        run: |
          git clone "https://slopp:${PAT}@github.com/dagster-io/internal"

      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          # Uncomment to pass through Github Action secrets as a JSON string of key-value pairs
          # env_vars: ${{ toJson(secrets) }}
          organization_id: ${{ secrets.ORGANIZATION_ID }}
          checkout_repo: 'false'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}